import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SPECS } from "./bounty-specs.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const USERNAME = /^[a-zA-Z0-9_]{3,20}$/;
const EM_DASH = /\u2014|\u2013/;

const reserved = new Set([
  "atlas_kt",
  "groundtruth",
  "shibuya_walker",
  "peripheral",
  "cartesian",
  "field_unit_07",
  "lowaltitude",
  "streetlevel_ml",
  "sensor_dense",
  "waypoint_zero",
  "curbside",
  "first_capture",
  "utopia_official",
  "admin",
  "utopia",
  "official",
  "utopia_data",
  "scout",
]);

function loadUsers() {
  return JSON.parse(readFileSync(join(here, "users.json"), "utf8"));
}

const rawBounties = [
  {
    id: "L01",
    title: "Pike Place, main arcade after 10",
    brief:
      "Need aisle geometry for indoor nav, not a food clip. After 10am, main arcade. How wide the walking lane really is, carts, people stopping, anything hanging into the path. Cut into a side hall if you can. Public aisles only, 20-40s.",
    category: "location",
    locationName: "Pike Place Market, Seattle, United States",
    lat: 47.6097,
    lng: -122.3421,
    radiusM: 400,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 0,
    deadlineDays: 21,
    launch: true,
    launchClips: 2,
    plannedClose: false,
  },
  {
    id: "L02",
    title: "LAX arrivals curb, commercial lane",
    brief:
      "Goal: curbside chaos for pickup stacks. TBIT or any arrivals commercial lane. Constraints: public sidewalk or island only, no roadway walking, daylight or dusk. Deliverable: one slow walk, buses, hotel vans, double parks, peds crossing between cars.",
    category: "location",
    locationName: "LAX arrivals curb, Los Angeles, United States",
    lat: 33.9416,
    lng: -118.4085,
    radiusM: 800,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 0,
    deadlineDays: 21,
    launch: true,
    launchClips: 4,
    plannedClose: false,
  },
  {
    id: "L03",
    title: "Canary Wharf service road after 18:00",
    brief:
      "Weekday after 18:00. Not the plaza postcard. Service road and loading bays: trucks, barriers, peds cutting through. Lighting change if you pass under a building. If it is dead, still film the empty bays.",
    category: "location",
    locationName: "Canary Wharf, London, United Kingdom",
    lat: 51.5054,
    lng: -0.0235,
    radiusM: 500,
    priceUsdc: 250,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 0,
    deadlineDays: 21,
    launch: true,
    launchClips: 3,
    plannedClose: false,
  },
  {
    id: "L04",
    title: "SFO arrivals curb, outer lane",
    brief:
      "1) Public outer curb only. 2) Pickup lane + crosswalk + a shuttle if one stops. 3) People dragging bags through traffic. 4) 20-30s. No roadway walking, no airside.",
    category: "location",
    locationName: "SFO arrivals curb, San Francisco, United States",
    lat: 37.6165,
    lng: -122.386,
    radiusM: 300,
    priceUsdc: 200,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 0,
    deadlineDays: 21,
    launch: true,
    launchClips: 5,
    plannedClose: false,
  },
  {
    id: "L05",
    title: "Interstate truck park, trailer angles",
    brief:
      "US rest area or truck park. Public lot. We need trailer angles and leftover space to reverse, not a headcount. Pan bays, any walkway through the lot, overflow on the access road.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 100,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 0,
    deadlineDays: 21,
    launch: true,
    launchClips: 1,
    plannedClose: false,
  },
  {
    id: "L06",
    title: "Tram 28, rush boarding",
    brief:
      "We are timing door clearance and platform gap, not tourism. Busy stop, peak, sidewalk only. One cycle: crush, dwell, second car, how people stand in the door.",
    category: "location",
    locationName: "Lisbon, Portugal",
    lat: 38.7139,
    lng: -9.1333,
    radiusM: 3000,
    priceUsdc: 50,
    chain: "usdc-solana",
    day: 0,
    timeMinutes: 0,
    deadlineDays: 21,
    launch: true,
    launchClips: 3,
    plannedClose: false,
  },
  {
    id: "L07",
    title: "Sidewalk driveway, parked-van occlude",
    brief:
      "A driveway that cuts a sidewalk, with a van or SUV parked so a walker (or a robot) cannot see the car until late. Walk the sidewalk, hold on the cut. No faces close. US or EU.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 25,
    chain: "usdg-robinhood",
    day: 0,
    timeMinutes: 0,
    deadlineDays: 21,
    launch: true,
    launchClips: 2,
    plannedClose: false,
  },
  {
    id: "M08",
    title: "I-10 downtown Houston, work zone",
    brief:
      "Please film a live work zone from a legal overpass or frontage. Cones, temp paint fighting old paint, lane drop. No walking the interstate. We train on temporary geometry.",
    category: "location",
    locationName: "I-10 downtown, Houston, United States",
    lat: 29.758,
    lng: -95.369,
    radiusM: 4000,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 660,
    deadlineDays: 18,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 2,
    closeTimeMinutes: 720,
  },
  {
    id: "M09",
    title: "Chicago Loop alley loading at dawn",
    brief:
      "Loop alley, before 08:00. Clearance for a box truck or a robot: docks, compactors, how much of the alley is left. Public ROW only.",
    category: "location",
    locationName: "The Loop, Chicago, United States",
    lat: 41.8819,
    lng: -87.6278,
    radiusM: 600,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 720,
    deadlineDays: 18,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 2,
    closeTimeMinutes: 840,
  },
  {
    id: "M10",
    title: "Times Square plaza, LED glare",
    brief:
      "Need a hard lighting scene, not a postcard. After 23:00, pedestrian plaza. LED bloom, people walking with no lanes, curb-free asphalt. Sidewalks / plaza only. If NYPD waves you on, go.",
    category: "location",
    locationName: "Times Square, New York, United States",
    lat: 40.758,
    lng: -73.9855,
    radiusM: 1200,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 780,
    deadlineDays: 16,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 3,
    closeTimeMinutes: 600,
  },
  {
    id: "M11",
    title: "Reading Terminal, interior aisles",
    brief:
      "Public aisles. Indoor nav: aisle width at walking speed, carts, wet spots, people stopping. Hanging signs that occlude. No counters from the inside.",
    category: "location",
    locationName: "Reading Terminal Market, Philadelphia, United States",
    lat: 39.9533,
    lng: -75.159,
    radiusM: 250,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 840,
    deadlineDays: 16,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 3,
    closeTimeMinutes: 700,
  },
  {
    id: "M12",
    title: "Weena tram, bike and truck mix",
    brief:
      "In front of Rotterdam Centraal / Weena. Tram, bikes, and trucks in the same frame. Daylight, 25-40s. If you step into the tracks we throw it out.",
    category: "location",
    locationName: "Weena, Rotterdam, Netherlands",
    lat: 51.923,
    lng: 4.469,
    radiusM: 2000,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 900,
    deadlineDays: 21,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 1,
    closeTimeMinutes: 900,
  },
  {
    id: "M13",
    title: "Chelsea Market, kitchen corridor",
    brief:
      "Main food corridor. Indoor topology: seating in the aisle, steam, people cutting across. Chest height. Not a food review.",
    category: "location",
    locationName: "Chelsea Market, New York, United States",
    lat: 40.7424,
    lng: -74.0061,
    radiusM: 150,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 960,
    deadlineDays: 14,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 2,
    closeTimeMinutes: 1000,
  },
  {
    id: "M14",
    title: "Flatbush and Atlantic, all modes",
    brief:
      "The junction. Buses, bikes, peds, trucks in one clip. Stay on the sidewalk. Late afternoon or overcast. If a cop says move, move.",
    category: "location",
    locationName: "Flatbush and Atlantic, Brooklyn, United States",
    lat: 40.684,
    lng: -73.977,
    radiusM: 800,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 1020,
    deadlineDays: 18,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 640,
  },
  {
    id: "M15",
    title: "SODO driveways cutting the sidewalk",
    brief:
      "SODO industrial block. Walk the sidewalk across two or more loading driveways. Trucks, mirrors, how late you see them. Stay off the yards.",
    category: "location",
    locationName: "SODO, Seattle, United States",
    lat: 47.581,
    lng: -122.327,
    radiusM: 400,
    priceUsdc: 500,
    chain: "usdc-base",
    day: 0,
    timeMinutes: 1080,
    deadlineDays: 16,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 3,
    closeTimeMinutes: 1080,
  },
  {
    id: "T16",
    title: "French Quarter alley after dark",
    brief:
      "Narrow alley, after dark. Low light, stools in the path, how much is actually walkable. Public alley only. 20s if the geometry is clear.",
    category: "location",
    locationName: "French Quarter, New Orleans, United States",
    lat: 29.9584,
    lng: -90.0644,
    radiusM: 80,
    priceUsdc: 250,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 540,
    deadlineDays: 14,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 3,
    closeTimeMinutes: 800,
  },
  {
    id: "T17",
    title: "Market Street, Muni in mixed traffic",
    brief:
      "Weekday midday. Muni tracks in the car lanes, bikes, peds stepping off the median. Marked crossings only. This is the mixed-traffic clip.",
    category: "location",
    locationName: "Market Street, San Francisco, United States",
    lat: 37.789,
    lng: -122.401,
    radiusM: 400,
    priceUsdc: 250,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 600,
    deadlineDays: 12,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 700,
  },
  {
    id: "T18",
    title: "De Keyserlei, tram in the roadway",
    brief:
      "Daylight. Tram in the roadway, bikes, shop spill. No interiors, no faces close. If a guard asks, stop.",
    category: "location",
    locationName: "De Keyserlei, Antwerp, Belgium",
    lat: 51.218,
    lng: 4.421,
    radiusM: 250,
    priceUsdc: 200,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 660,
    deadlineDays: 14,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T19",
    title: "Oslo opera roof, unmarked slope",
    brief:
      "Public marble roof. No lanes, slope changing underfoot, people walking every direction. Overcast is fine. If it is closed, do not climb a barrier.",
    category: "location",
    locationName: "Oslo Opera House, Norway",
    lat: 59.9075,
    lng: 10.753,
    radiusM: 200,
    priceUsdc: 200,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 720,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 3,
    closeTimeMinutes: 900,
  },
  {
    id: "T20",
    title: "Vieux-Port fish stall reset",
    brief:
      "Quai des Belges, morning. Wet ground, crates as obstacles, people carrying ice. Public quay. Empty tables still useful.",
    category: "location",
    locationName: "Vieux-Port, Marseille, France",
    lat: 43.295,
    lng: 5.374,
    radiusM: 200,
    priceUsdc: 150,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 780,
    deadlineDays: 12,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T21",
    title: "Denver Union Station from the hall",
    brief:
      "Great hall or the gates. Crowd flow, rolling luggage, glass reflections. Stay ticket-side legal. Dead hall still counts.",
    category: "location",
    locationName: "Union Station, Denver, United States",
    lat: 39.7533,
    lng: -105.0001,
    radiusM: 200,
    priceUsdc: 100,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 840,
    deadlineDays: 14,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 780,
  },
  {
    id: "T22",
    title: "Andel tram island, Prague",
    brief:
      "Andel island. Platform gap, arriving car, where people stand vs the yellow line. Behind the line. Arrival + departure if you can.",
    category: "location",
    locationName: "Andel, Prague, Czechia",
    lat: 50.0705,
    lng: 14.404,
    radiusM: 150,
    priceUsdc: 75,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 900,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T23",
    title: "Storefront queue on the sidewalk",
    brief:
      "A queue that eats the sidewalk. How much walking lane is left, door swing, people stepping into the street. Morning or lunch. Do not block the door.",
    category: "object",
    locationName: "East Village, New York, United States",
    lat: 40.7282,
    lng: -73.9942,
    radiusM: 1500,
    priceUsdc: 50,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 960,
    deadlineDays: 12,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T24",
    title: "Bike-share dock blocking the walk",
    brief:
      "Citibike / Velib / Santander. Whole dock plus leftover sidewalk width. Overflow locked to racks or poles. 10s if the blockage is readable.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 25,
    chain: "usdc-solana",
    day: 1,
    timeMinutes: 1020,
    deadlineDays: 9,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T25",
    title: "Convenience door and floor change",
    brief:
      "Automatic or heavy door into a corner store, then the floor change (tile, mat, lip). From just inside if they allow it. Buy something if asked.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 20,
    chain: "usdg-robinhood",
    day: 1,
    timeMinutes: 1080,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T26",
    title: "Bulk-trash blocking the sidewalk",
    brief:
      "Bulk day. Walk one suburban block. Couches and appliances that force a walker into the street. One side.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 15,
    chain: "usdc-solana",
    day: 1,
    timeMinutes: 1140,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T27",
    title: "Floating bus stop, bike conflict",
    brief:
      "Need a bus bulb or floating stop where the bike lane goes behind the shelter. Ped vs bike vs bus. Night is fine.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 10,
    chain: "usdc-solana",
    day: 1,
    timeMinutes: 1180,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T28",
    title: "Faded lane lines, suburban arterial",
    brief:
      "A multi-lane suburban road where the paint is almost gone. Include a turn pocket if there is one. Public shoulder or sidewalk. Don't stand in the lane.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 5,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 1220,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T29",
    title: "No-parking paint with a car on it",
    brief:
      "Red or yellow curb, hydrant or fire lane, and a car sitting on it. 5-10s. Encroachment is the point.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 3,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 1260,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "T30",
    title: "Work-zone sandwich board in a lane",
    brief:
      "Temporary A-frame or diamond sign plus cones in or next to a travel lane. One setup. Do not walk the closed lane.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 2,
    chain: "usdc-base",
    day: 1,
    timeMinutes: 1300,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "W31",
    title: "North End, delivery van in a narrow",
    brief:
      "North End. A van or box truck occupying most of a one-way. Leftover width, stoops, whether a walker has to step out. Stay off private stoops.",
    category: "location",
    locationName: "North End, Boston, United States",
    lat: 42.3647,
    lng: -71.0542,
    radiusM: 200,
    priceUsdc: 250,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 540,
    deadlineDays: 12,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 900,
  },
  {
    id: "W32",
    title: "Hamburg Speicherstadt canal walk",
    brief:
      "Marked quay. Cobbles, canal edge with no curb, a bridge. Moored craft if there. Ground plane + drop-off, not a boat tour.",
    category: "location",
    locationName: "Speicherstadt, Hamburg, Germany",
    lat: 53.5444,
    lng: 9.999,
    radiusM: 400,
    priceUsdc: 200,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 600,
    deadlineDays: 12,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 960,
  },
  {
    id: "W33",
    title: "Howard Street, light rail in traffic",
    brief:
      "Light rail in the roadway. Daylight. Stay on the sidewalk. If you only get a parked train, still send it.",
    category: "location",
    locationName: "Howard Street, Baltimore, United States",
    lat: 39.289,
    lng: -76.615,
    radiusM: 500,
    priceUsdc: 200,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 660,
    deadlineDays: 11,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1020,
  },
  {
    id: "W34",
    title: "Lake Street L from the sidewalk",
    brief:
      "Under the Lake Street L. Columns occluding the sidewalk and the street. Do not climb. If CTA tells you to move, leave.",
    category: "location",
    locationName: "Lake Street L, Chicago, United States",
    lat: 41.885,
    lng: -87.628,
    radiusM: 400,
    priceUsdc: 150,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 720,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1080,
  },
  {
    id: "W35",
    title: "Stockholm Slussen rebuild edge",
    brief:
      "Public edge of Slussen. Temp walkways, hoarding, a grade change. No site access. Temporary geometry is the job.",
    category: "location",
    locationName: "Slussen, Stockholm, Sweden",
    lat: 59.3205,
    lng: 18.072,
    radiusM: 300,
    priceUsdc: 100,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 780,
    deadlineDays: 12,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1140,
  },
  {
    id: "W36",
    title: "Night bus layover bay",
    brief:
      "After 21:00, layover bay. Buses reversing or parked at an angle. Sidewalk. Night service city.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 75,
    chain: "usdc-solana",
    day: 2,
    timeMinutes: 840,
    deadlineDays: 9,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1200,
  },
  {
    id: "W37",
    title: "Glass storefront at night, reflections",
    brief:
      "A glass shopfront after dark. Reflections of headlights and streetlights vs what is actually behind the glass. Street. No interiors.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 50,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 900,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1260,
  },
  {
    id: "W38",
    title: "Petrol station canopy and pumps",
    brief:
      "Public forecourt. Canopy, pump islands, cars cutting between bays, peds walking to the kiosk. No pay-terminal close-ups. Any brand.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 25,
    chain: "usdc-solana",
    day: 2,
    timeMinutes: 960,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 3,
    closeTimeMinutes: 1260,
  },
  {
    id: "W39",
    title: "Automatic door, glass vestibule",
    brief:
      "Bank or office automatic door plus the glass vestibule. How it opens, who waits, reflections. No PIN-pad close-ups.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 20,
    chain: "usdg-robinhood",
    day: 2,
    timeMinutes: 1020,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "W40",
    title: "School run, street not playground",
    brief:
      "Dismissal, street only. Double parks, crossing-guard signs, flashers. Do not point the camera at children. Facade and roadway are the subject.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 15,
    chain: "usdc-solana",
    day: 2,
    timeMinutes: 1080,
    deadlineDays: 9,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "W41",
    title: "Laundromat machines from the door",
    brief:
      "Open doorway. Cart, door lip, wet floor if there is one. Do not walk the aisles if staff object. 30s max.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 15,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 1120,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 800,
  },
  {
    id: "W42",
    title: "Parking meter or kiosk state",
    brief:
      "Pay kiosk or meters plus the bays. Occupied vs empty, a car pulling in if you catch one. One side.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 10,
    chain: "usdc-solana",
    day: 2,
    timeMinutes: 1160,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "W43",
    title: "Park path, stairs versus ramp",
    brief:
      "A public park entrance that has both stairs and a ramp. Film the split from outside. Keep faces small.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 5,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 1200,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "W44",
    title: "Sunken curb inlet, bike line",
    brief:
      "A curb inlet or grate in a bike lane or door zone. Sunken or proud of the asphalt. 5s. Any street.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 3,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 1240,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "W45",
    title: "Store loading ramp on the sidewalk",
    brief:
      "A metal ramp or plate from a shop down to the sidewalk. Slope, leftover width, anyone using it. One door.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 2,
    chain: "usdc-base",
    day: 2,
    timeMinutes: 1280,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "H46",
    title: "Grand Central from the concourse",
    brief:
      "Main concourse or overbridge. Crowd flow, luggage, people stopping in the middle. A train in the throat if you catch one. No trackbed.",
    category: "location",
    locationName: "Grand Central, New York, United States",
    lat: 40.7527,
    lng: -73.9772,
    radiusM: 8000,
    priceUsdc: 250,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 540,
    deadlineDays: 12,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 600,
  },
  {
    id: "H47",
    title: "Union Square, stairs vs elevator",
    brief:
      "Street pavilion. Stairs, elevator, and leftover sidewalk in one clip. You do not need to go through the turnstiles.",
    category: "location",
    locationName: "Union Square, New York, United States",
    lat: 40.7359,
    lng: -73.9911,
    radiusM: 800,
    priceUsdc: 200,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 600,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 660,
  },
  {
    id: "H48",
    title: "30th Street Station, taxi curb",
    brief:
      "Taxi / rideshare curb. Cars stacked, peds between bumpers, bags. Daylight. Do not argue with security.",
    category: "location",
    locationName: "30th Street Station, Philadelphia, United States",
    lat: 39.9558,
    lng: -75.182,
    radiusM: 400,
    priceUsdc: 200,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 660,
    deadlineDays: 14,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 720,
  },
  {
    id: "H49",
    title: "Valletta waterfront warehouses",
    brief:
      "Valletta or Pinto Wharf. Tight stone street or quay, no painted lanes, cafe spill. Signed private pontoons are out.",
    category: "location",
    locationName: "Valletta, Malta",
    lat: 35.896,
    lng: 14.512,
    radiusM: 400,
    priceUsdc: 150,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 720,
    deadlineDays: 11,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 780,
  },
  {
    id: "H50",
    title: "Whitehall ferry ramp and crowd",
    brief:
      "The ramp or the hold. Slope, luggage wheels, people stopping. Public access. Empty hall still counts.",
    category: "location",
    locationName: "Whitehall Terminal, New York, United States",
    lat: 40.701,
    lng: -74.013,
    radiusM: 4000,
    priceUsdc: 100,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 780,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 840,
  },
  {
    id: "H51",
    title: "Tram tracks in a car lane",
    brief:
      "Street tram or trolley in a mixed lane. Rails, a car sharing the lane, the stop if it is nearby. Any US or EU city with overhead wire.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 75,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 840,
    deadlineDays: 9,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 900,
  },
  {
    id: "H52",
    title: "Food truck row, lunch line",
    brief:
      "Food truck row at lunch. People walking between bumpers, generators, leftover aisle. Polite distance. Stop if asked.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 50,
    chain: "usdc-solana",
    day: 3,
    timeMinutes: 900,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 960,
  },
  {
    id: "H53",
    title: "24-hour convenience aisle end",
    brief:
      "Just inside a 24h store. One aisle end, fridge line, a cart if there is one. Stock gaps and occlusion. Buy something if asked.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 25,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 960,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1000,
  },
  {
    id: "H54",
    title: "Scooter or moped parking tangle",
    brief:
      "Dense scooter or moped pile on a sidewalk. Count them, leftover walking width. Any dense US or EU city.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 20,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 1020,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1040,
  },
  {
    id: "H55",
    title: "Wet floor after mop-down",
    brief:
      "Grocery or market hall after mop-down. Reflections, leftover crates, how slippery it looks. Public aisle. No back rooms.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 15,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 1080,
    deadlineDays: 9,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1100,
  },
  {
    id: "H56",
    title: "Scaffolding tunnel on the sidewalk",
    brief:
      "A scaffolding tunnel. Reduced width, posts, lighting change. Walk 5-10m. Any US or EU city.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 10,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 1120,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1120,
  },
  {
    id: "H57",
    title: "Overflow bin blocking the walk",
    brief:
      "A bin plus bags on the ground that eat the sidewalk. One setup. Do not rummage.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 5,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 1160,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1160,
  },
  {
    id: "H58",
    title: "Proud or sunken utility cover",
    brief:
      "A manhole or cover that sits proud or sunken vs the pavement. Hold 2s. Trip / wheel hazard is the point.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 5,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 1200,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1180,
  },
  {
    id: "H59",
    title: "Curb cut at a corner",
    brief:
      "Corner curb cut. Slope, tactile if any, damaged lip. The adjacent crossing. Damaged is better than perfect.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 3,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 1240,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1200,
  },
  {
    id: "H60",
    title: "A-frame signs eating the sidewalk",
    brief:
      "Two or more sandwich boards or A-frames that pinch the walking lane. Alley or street. Layering is fine, blockage is the job.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 2,
    chain: "usdc-base",
    day: 3,
    timeMinutes: 1280,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: false,
  },
  {
    id: "F61",
    title: "Santa Monica, sidewalk plus driveways",
    brief:
      "Ocean-facing sidewalk with driveway cuts and bikes. Path width, cars nosing out. Late afternoon if you can. No pier attractions from inside.",
    category: "location",
    locationName: "Santa Monica Pier, United States",
    lat: 34.0094,
    lng: -118.497,
    radiusM: 1500,
    priceUsdc: 200,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 540,
    deadlineDays: 12,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1260,
  },
  {
    id: "F62",
    title: "Helsinki market square stalls",
    brief:
      "Kauppatori. Stall spacing, people cutting through, cobbles, a ferry behind if it is there. Empty seasonal stalls still count.",
    category: "location",
    locationName: "Kauppatori, Helsinki, Finland",
    lat: 60.1675,
    lng: 24.9528,
    radiusM: 200,
    priceUsdc: 150,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 600,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1280,
  },
  {
    id: "F63",
    title: "BeltLine, bikes vs peds no lanes",
    brief:
      "One BeltLine segment. Shared path, no paint, bikes vs peds vs strollers. Stay on the trail. Say the nearest crossing if you remember it.",
    category: "location",
    locationName: "Atlanta BeltLine, United States",
    lat: 33.763,
    lng: -84.361,
    radiusM: 2000,
    priceUsdc: 100,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 660,
    deadlineDays: 10,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1300,
  },
  {
    id: "F64",
    title: "Construction gate, trucks in and out",
    brief:
      "Public fence line at a site gate. Trucks entering or waiting, a flagger if there is one, leftover sidewalk. No site entry.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 75,
    chain: "usdc-solana",
    day: 4,
    timeMinutes: 720,
    deadlineDays: 9,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1320,
  },
  {
    id: "F65",
    title: "Low awning or scaffold over the walk",
    brief:
      "An awning, pipe, or scaffold that drops the clearance over a sidewalk. Tilt from walking height. No apartment interiors.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 75,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 760,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1340,
  },
  {
    id: "F66",
    title: "Cables across the sidewalk",
    brief:
      "A cable run or hose across a public path, plus the generator or tap if you can see it. Do not touch it. Trip hazard is the job.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 50,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 800,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1360,
  },
  {
    id: "F67",
    title: "Underpass, lighting drop",
    brief:
      "Walk from daylight into an underpass and out. Lighting drop, columns, leftover width. Do not block a lane.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 50,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 840,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1370,
  },
  {
    id: "F68",
    title: "Library entrance, stairs and ramp",
    brief:
      "Main library or civic building. Stairs and a ramp in one clip, doors open or not. Street or plaza. Leave if security says so.",
    category: "location",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 25,
    chain: "usdc-solana",
    day: 4,
    timeMinutes: 880,
    deadlineDays: 9,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1385,
  },
  {
    id: "F69",
    title: "Heavy door or revolving door, street",
    brief:
      "A revolving door or a heavy street door on a church, bank, or hall. How people get through it. Not a service inside.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 25,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 920,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1380,
  },
  {
    id: "F70",
    title: "EV slow charger on a lamp post",
    brief:
      "Lamp-post or bollard charger. Plug type, a connected car if there is one, leftover sidewalk. Street, not a gated garage.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 20,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 960,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1390,
  },
  {
    id: "F71",
    title: "Parcel locker on the sidewalk",
    brief:
      "Sidewalk locker. Door bank, someone using it if you catch them, leftover walking width. Street only.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 20,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 1000,
    deadlineDays: 8,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1400,
  },
  {
    id: "F72",
    title: "Shared e-bike dump at a corner",
    brief:
      "Dockless pile at a corner. Count them, leftover sidewalk, whether they spill into the bike lane.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 15,
    chain: "usdg-robinhood",
    day: 4,
    timeMinutes: 1040,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1410,
  },
  {
    id: "F73",
    title: "Kiosk and stools on the sidewalk",
    brief:
      "A key / phone / lottery kiosk plus stools. How much walking lane is left. Any US or EU city.",
    category: "object",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 15,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 1080,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1420,
  },
  {
    id: "F74",
    title: "Tight service alley, clearance",
    brief:
      "A service alley too narrow for two people to pass cleanly. Compressors, bins, leftover width. Do not enter buildings.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 10,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 1120,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1430,
  },
  {
    id: "F75",
    title: "Speed bump plus approach markings",
    brief:
      "A speed bump or table plus the warning paint on the approach. A few meters before it. Cars hitting it if you catch one.",
    category: "coverage",
    locationName: null,
    lat: null,
    lng: null,
    radiusM: null,
    priceUsdc: 10,
    chain: "usdc-base",
    day: 4,
    timeMinutes: 1160,
    deadlineDays: 7,
    launch: false,
    launchClips: 0,
    plannedClose: true,
    closeDay: 4,
    closeTimeMinutes: 1435,
  },
];

/**
 * Deadlines are remixed here so the board shows a spread of durations
 * (3 days up to 21) instead of everything sitting at 21 days. Bounties the
 * worker plans to close must outlive their close slot.
 */
const OPEN_DEADLINES = [3, 5, 7, 10, 14, 21];
const CLOSE_DEADLINES = [5, 6, 7, 10, 14, 21];

function mixedDeadline(row, index) {
  const minDays = row.plannedClose ? row.closeDay - row.day + 1 : 0;
  const pool = (row.plannedClose ? CLOSE_DEADLINES : OPEN_DEADLINES).filter(
    (days) => days >= minDays
  );
  return pool[index % pool.length];
}

const bounties = rawBounties.map((row, index) => {
  const spec = SPECS[row.id];
  if (!spec) throw new Error(`Missing spec ${row.id}`);
  return { ...row, ...spec, deadlineDays: mixedDeadline(row, index) };
});

const CREATOR_KINDS = ["ai_lab", "robotics_team", "private"];

function assignCreators(users) {
  const launchUsers = users.filter((u) => u.launch);
  const laterUsers = users.filter((u) => !u.launch);
  let laterIndex = 0;
  return bounties.map((bounty, index) => {
    if (!CREATOR_KINDS.includes(bounty.creatorKind)) {
      throw new Error(`bad kind ${bounty.id}`);
    }
    const funder = bounty.launch
      ? launchUsers[index].username
      : laterUsers[laterIndex++ % laterUsers.length].username;
    return { ...bounty, funder };
  });
}

function validate(users, rows) {
  const errors = [];
  const names = new Set();
  for (const user of users) {
    if (!USERNAME.test(user.username)) errors.push(`user ${user.username}`);
    const key = user.username.toLowerCase();
    if (names.has(key)) errors.push(`dup user ${user.username}`);
    names.add(key);
    if (reserved.has(key) || /^0x[a-f0-9]{6,}$/.test(key)) {
      errors.push(`reserved ${user.username}`);
    }
  }
  if (users.length !== 300) errors.push(`users ${users.length}`);
  if (users.filter((u) => u.launch).length !== 27) errors.push("launch users");
  if (users.some((u) => u.lab || u.style === "lab")) {
    errors.push("users.json still has lab accounts");
  }

  if (rows.length !== 75) errors.push(`bounties ${rows.length}`);
  const priceCount = {};
  const dayReward = [0, 0, 0, 0, 0];
  let sol = 0;
  let rh = 0;
  let base = 0;
  let openReward = 0;
  let closeReward = 0;
  let launchClips = 0;
  for (const row of rows) {
    if (row.title.length < 8 || row.title.length > 90) {
      errors.push(`title ${row.id}`);
    }
    if (row.brief.length < 40 || row.brief.length > 1200) {
      errors.push(`brief ${row.id} ${row.brief.length}`);
    }
    if (
      /\b\d+\s*-?\s*\d*\s*s(ec(ond)?s?)?\b/i.test(row.brief) ||
      /\b(twenty|30|forty)\s*seconds?\b/i.test(row.brief)
    ) {
      errors.push(`duration ${row.id}`);
    }
    if (EM_DASH.test(row.title) || EM_DASH.test(row.brief)) {
      errors.push(`dash ${row.id}`);
    }
    if (/, and\b/.test(row.title) || /, and\b/.test(row.brief)) {
      errors.push(`comma-and ${row.id}`);
    }
    if (!["location", "object", "coverage"].includes(row.category)) {
      errors.push(`cat ${row.id}`);
    }
    if (!CREATOR_KINDS.includes(row.creatorKind)) {
      errors.push(`kind ${row.id}`);
    }
    if (!names.has(row.funder?.toLowerCase())) errors.push(`funder ${row.id}`);
    if (row.priceUsdc >= 150 && row.chain !== "usdc-base") {
      errors.push(`chain big ${row.id}`);
    }
    if (
      (row.chain === "usdc-solana" || row.chain === "usdg-robinhood") &&
      row.priceUsdc > 75
    ) {
      errors.push(`float ${row.id}`);
    }
    priceCount[row.priceUsdc] = (priceCount[row.priceUsdc] ?? 0) + 1;
    dayReward[row.day] += row.priceUsdc;
    if (row.chain === "usdc-solana") sol += 1;
    else if (row.chain === "usdg-robinhood") rh += 1;
    else if (row.chain === "usdc-base") base += 1;
    else errors.push(`bad chain ${row.id}`);
    if (row.plannedClose) closeReward += row.priceUsdc;
    else openReward += row.priceUsdc;
    launchClips += row.launchClips;
    if (row.plannedClose) {
      if (row.closeDay < row.day) errors.push(`close before post ${row.id}`);
      if (row.closeDay === row.day && row.closeTimeMinutes <= row.timeMinutes) {
        errors.push(`close same slot ${row.id}`);
      }
    }
  }

  const expectPrices = {
    2: 3, 3: 3, 5: 4, 10: 5, 15: 6, 20: 5, 25: 6, 50: 6, 75: 5,
    100: 5, 150: 4, 200: 8, 250: 5, 500: 10,
  };
  for (const [price, count] of Object.entries(expectPrices)) {
    if (priceCount[Number(price)] !== count) {
      errors.push(`price ${price} got ${priceCount[price]}`);
    }
  }
  if (base !== 60 || sol !== 11 || rh !== 4) {
    errors.push(`chains ${base}/${sol}/${rh}`);
  }
  if (dayReward[0] !== 5625) errors.push(`day0 ${dayReward[0]}`);
  if (dayReward[1] !== 1355) errors.push(`day1 ${dayReward[1]}`);
  if (dayReward[2] !== 1120) errors.push(`day2 ${dayReward[2]}`);
  if (dayReward[3] !== 1110) errors.push(`day3 ${dayReward[3]}`);
  if (dayReward[4] !== 840) errors.push(`day4 ${dayReward[4]}`);
  if (openReward !== 2237) errors.push(`open ${openReward}`);
  if (closeReward !== 7813) errors.push(`close ${closeReward}`);
  if (launchClips !== 20) errors.push(`clips ${launchClips}`);
  if (rows.filter((r) => r.launch).length !== 7) errors.push("launch count");
  if (rows.filter((r) => !r.plannedClose).length !== 25) {
    errors.push("open count");
  }

  const kindCount = { ai_lab: 0, robotics_team: 0, private: 0 };
  for (const row of rows) kindCount[row.creatorKind] += 1;
  for (const [kind, count] of Object.entries(kindCount)) {
    if (count !== 25) errors.push(`${kind} ${count}`);
  }

  return { errors, base, sol, rh, openReward, closeReward, dayReward };
}

const users = loadUsers();
const rows = assignCreators(users);
const report = validate(users, rows);
if (report.errors.length) {
  console.error(report.errors.join("\n"));
  process.exit(1);
}

writeFileSync(join(here, "bounties.json"), `${JSON.stringify(rows, null, 2)}\n`);
console.log(
  JSON.stringify(
    {
      users: users.length,
      launchUsers: users.filter((u) => u.launch).length,
      bounties: rows.length,
      kinds: {
        ai_lab: rows.filter((r) => r.creatorKind === "ai_lab").length,
        robotics_team: rows.filter((r) => r.creatorKind === "robotics_team")
          .length,
        private: rows.filter((r) => r.creatorKind === "private").length,
      },
      chains: `${report.base}/${report.sol}/${report.rh}`,
      open: report.openReward,
      closed: report.closeReward,
      days: report.dayReward,
    },
    null,
    2
  )
);
