/** Mixed handles: real US/UK names, birth years, 0x prefixes, and IGNs. */

const LAUNCH = [
  ["0xDaegon", "handle"],
  ["jake_97", "real"],
  ["Emma_uk", "real"],
  ["0xMiles", "handle"],
  ["sarah1999", "real"],
  ["chris_b", "real"],
  ["jexu", "handle"],
  ["kaelZor", "handle"],
  ["Seltz", "handle"],
  ["oliver88", "real"],
  ["0xNash", "handle"],
  ["lucy_02", "real"],
  ["JamesT", "real"],
  ["fyro", "handle"],
  ["harry1998", "real"],
  ["Amelia_w", "real"],
  ["pexu", "handle"],
  ["0xReed", "handle"],
  ["nortz", "handle"],
  ["Callum91", "real"],
  ["voxz", "handle"],
  ["Freya_uk", "real"],
  ["Tennzyk", "handle"],
  ["veyl7", "numbered"],
  ["LiamT", "real"],
  ["orix_na", "handle"],
  ["mezq", "handle"],
];

const REAL_LATER = [
  ["noah_nyc", "real"],
  ["OliviaM", "real"],
  ["mason1997", "real"],
  ["Harper_uk", "real"],
  ["ethan02", "real"],
  ["SophiaK", "real"],
  ["jack_88", "real"],
  ["CharlotteW", "real"],
  ["isla1996", "real"],
  ["george_b", "real"],
  ["Megan91", "real"],
  ["ryan_uk", "real"],
  ["chloe2001", "real"],
  ["NathanJ", "real"],
  ["grace_02", "real"],
  ["ben_m", "real"],
  ["tyler88", "real"],
  ["hannah_w", "real"],
  ["Connor97", "real"],
  ["katie_uk", "real"],
  ["dylan1995", "real"],
  ["laurenB", "real"],
  ["josh_03", "real"],
  ["SophieR", "real"],
  ["matt1994", "real"],
  ["ellie_uk", "real"],
  ["sam_h", "real"],
  ["rachel02", "real"],
  ["tom_w", "real"],
  ["alice1998", "real"],
  ["dan_uk", "real"],
  ["molly_b", "real"],
  ["will88", "real"],
  ["nina_02", "real"],
  ["owen1993", "real"],
  ["ivy_uk", "real"],
  ["leo_m", "real"],
  ["ruby2000", "real"],
  ["finn_97", "real"],
  ["chloeT", "real"],
];

const HEX_LATER = [
  ["0xCole", "handle"],
  ["0xQuinn", "handle"],
  ["0xBlake", "handle"],
  ["0xDrew", "handle"],
  ["0xKane", "handle"],
  ["0xKnox", "handle"],
  ["0xBeau", "handle"],
  ["0xJude", "handle"],
  ["0xRhett", "handle"],
  ["0xShane", "handle"],
  ["0xTroy", "handle"],
  ["0xWade", "handle"],
  ["0xClay", "handle"],
  ["0xGrant", "handle"],
  ["0xHayes", "handle"],
  ["0xScott", "handle"],
];

const NUMBERED_LATER = [
  ["ryzan98", "numbered"],
  ["prenn94", "numbered"],
  ["saxir99", "numbered"],
  ["kettz88", "numbered"],
  ["lorik91", "numbered"],
  ["fynor94", "numbered"],
  ["rillo99", "numbered"],
  ["jirun94", "numbered"],
  ["matsuu1998", "numbered"],
  ["edrik94", "numbered"],
  ["gleeb99", "numbered"],
  ["inzel98", "numbered"],
  ["aybek94", "numbered"],
  ["rukel99", "numbered"],
  ["eftor94", "numbered"],
  ["blixx07", "numbered"],
  ["Krynova92", "numbered"],
  ["zevik2001", "numbered"],
  ["keldn88", "numbered"],
  ["Wexilar95", "numbered"],
  ["Mirqoss03", "numbered"],
  ["threxel99", "numbered"],
  ["Zhuro91", "numbered"],
  ["shivqin02", "numbered"],
];

const HANDLES = [
  "qorvindel", "tynn", "braxx", "luro", "vortakelunqix", "jaelX", "kovitTwo",
  "fenqorviltxen", "jomqelravnoxi", "hukzovarinqel", "zairNokai", "dinqorvelt",
  "beqziranox", "Nylixorven", "Korve", "aexl", "vinnqelra", "wolqiravenx",
  "plevnokai", "tepqorvaln", "drex_tv", "Kaivn", "rizqenholdx", "nylor",
  "vexq", "Toril", "felqorin", "brinX", "Yalvo", "novir", "Ziren", "palqorin",
  "wrenX", "nuvqoratel", "Myxen", "jael_qq", "sypqiravel", "OrvekTV",
  "mekzovarinq", "rulvo", "SeniX", "qiven", "arox", "Cyrelok", "dovix_jp",
  "Grelkone", "hyvox", "JaskqLive", "kylor", "haskoTwo", "Brimz", "yutoq",
  "KelviFPS", "sproq", "Flixn", "qaril", "zestQ", "munkq", "Jonsz",
  "jalqorvent", "skovn", "Blekz", "nuriq", "kopqiravenx", "wibqeltron",
  "wesserqueue", "daelikNight", "Hurvqenra", "dafzorvelq", "ceqirnoval",
  "slyqorin", "virqelston", "branq", "nobqiravel", "trelq", "KivorOne",
  "raezn", "solvi", "daskaTwo", "Murov", "poqen", "wrylo", "HexirByte",
  "calno", "Neltorin", "prael", "YolviClip", "bexir", "KriloHold", "nivor",
  "wurvoraen", "Driqorin", "peqon", "OvaziSwap", "rexol", "StyroPeek",
  "plovi", "molko", "YavirShot", "qinzo", "neoliraen", "ZivorHold", "tevno",
  "ovoliraen", "xumqorvelt", "nirexonq", "YorviMain", "sivno", "yilqenravx",
  "mivoranq", "VekirDiff", "spardzTV", "gomqiravel", "hunqorvelt", "Qoqen",
  "predzqHS", "awpi", "Tapzo", "nizq", "Bobeq", "ArctizCore", "veltorin",
  "knoqel", "DravnLine", "yelkz", "prowq", "MizraqWin", "tovennik", "sklir",
  "bexolt", "JarnikGo", "quovel", "heshq", "lirvekhold", "ponxq", "wujik",
  "daesq", "KronviSet", "slyvekor", "neqo", "BravikOff", "zorqinel", "tullv",
  "kivra", "RaelonUp", "sovik", "durnq", "MavrelOk", "poqis", "wryvekor",
  "helzikon", "CalvornX", "jurik", "NelvikPro", "cobqTwo", "Phynz", "quixn",
  "Rhov", "ghint", "Xeltq", "xivoq", "Xorel", "xupq", "xymn", "Xebq",
  "xoqir", "xalv", "Xirn", "chuln", "Chavq", "thulq", "Thov", "thix",
  "Twixn", "dwyn", "Swelq", "swynx", "ghuln", "Phulq", "phoxn", "Rhuln",
  "rhex", "Bhex", "gluqorin", "Clentorqq", "cluqorin", "IggyqinTV",
  "ozzyqHold", "Uzzi", "izzq", "olricTwo", "balqorin", "colvq", "elqir",
  "falqorin", "galqn", "ilqor", "stebqenra", "gruqorin", "cruvnora",
  "fruqorin", "sneltorqq", "sceltorqq", "odrikonqq", "ubrikonqq", "Yphelorqq",
  "pikzelravn", "Jupqin", "loopq", "Myphor", "oztikTwo", "pyghn", "Soolq",
  "tuvek", "Uvqor", "wyndq", "Zuultenra", "BoqirHold", "lodqiraven", "ewolq",
  "Guvelenra", "iwolt", "KuvelHold", "lyqor", "Mweltenra", "owelt",
  "RuvelHold", "uwelt", "Qezlorin", "zafvorqeln", "ibzqorin", "Olteq",
  "pyzno", "Aeqon", "zimqorin", "Nuqil", "ybrek", "Cizel", "uqron",
  "eqmirstonq", "Smiqorin", "rilqenavox", "wybeq", "Lazuq", "irvex",
  "Pozel", "ghenq", "tumqorveli", "Drizq", "blixx", "keldn", "Wexilar",
  "jaqZ", "Mirqoss", "threxel", "Zhuro", "shivqin", "qorvinel",
];

const extras = [];
const taken = new Set(LAUNCH.map(([name]) => name.toLowerCase()));
for (const row of [
  ...REAL_LATER,
  ...HEX_LATER,
  ...NUMBERED_LATER,
  ...HANDLES.map((name) => [name, "handle"]),
]) {
  const key = row[0].toLowerCase();
  if (taken.has(key)) continue;
  taken.add(key);
  extras.push(row);
}

export const NAMES = [...LAUNCH, ...extras.slice(0, 273)];
